### ISSUE TITLE
PCB 吸取治具機構

### ISSUE THREAD

**Issue by TMCFrankLee** [NickLee475/3S-FOCI-TMC#10]
PCB 吸取治具機構圖檔確認及發包製作
[AJI_PCB_ASM-01.pdf](https://github.com/NickLee475/3S-FOCI-TMC/files/10163459/AJI_PCB_ASM-01.pdf)

**Comment by Foci-Alvin** [comment]
請問機構圖是要請Herman 再確認並由FOCI 發包製作?

**Comment by TMCFrankLee** [comment]
> 請問機構圖是要請Herman 再確認並由FOCI 發包製作?

@3S-En 進行確認後由廣化發包製作

**Comment by 3S-En** [comment]
1.請問除了加工件以外，上述的配件也是由廣化 採買嗎?還是目前上詮有相關配件。

另外圖面上有些問題想釐清
1. 螺帽干涉
![螺帽干涉](https://user-images.githubusercontent.com/92710332/206061807-51339162-7783-49e7-9a30-b174d1ff50bc.jpg)
。
2. 圖面問題確認
![圖面問題2](https://user-images.githubusercontent.com/92710332/206061952-ddef01a0-d7e8-4f54-9200-20b4d54b270b.png)
![圖面問題1](https://user-images.githubusercontent.com/92710332/206061957-954bb587-9e38-4a76-9470-80f0b9a5ca30.png)

**Comment by Herman1114414** [comment]
1.配件部份上詮沒有多的備品
2.PCB載板由機檯上拆下繪製，如有加工上的需求可以提供3D圖修改

**Comment by Herman1114414** [comment]
![image](https://user-images.githubusercontent.com/118881468/206070154-be89e0a4-ace8-4d45-8d46-d87e380804b0.jpeg)

**Comment by AvenisSung** [comment]
因為要透過我們公司系統發包，圖號必須依照我們ERP規範。
圖面部分有稍微調整，避免裝配問題。
[XX04A-011.PDF](https://github.com/NickLee475/3S-FOCI-TMC/files/10183105/XX04A-011.PDF)
[XX04A-012.PDF](https://github.com/NickLee475/3S-FOCI-TMC/files/10183108/XX04A-012.PDF)
[XX04A-013.PDF](https://github.com/NickLee475/3S-FOCI-TMC/files/10183812/XX04A-013.PDF)

**Comment by AvenisSung** [comment]
快速接頭應該朝外(面向機台後方)，型號修正
固定件會修改，內孔至少要開11mm以上
![221208_1650](https://user-images.githubusercontent.com/118797964/206401664-95dec231-cf57-40dd-9d63-e763d561356a.png)

**Comment by TMCFrankLee** [comment]
@Herman1114414 可以確認一下嗎?
https://github.com/NickLee475/3S-FOCI-TMC/issues/10#issuecomment-1342200149
https://github.com/NickLee475/3S-FOCI-TMC/issues/10#issuecomment-1342288503

**Comment by Herman1114414** [comment]
3D圖配置若無干涉就沒問題

**Comment by 3S-En** [comment]
@TMCFrankLee @Herman1114414 

目前PCB治具上的真空吸盤交期45天! 
請問貴司還有相關備品嗎?
我司會持續尋找替代品。

ZP3-T04BN-A5 真空吸盤交期45天

![image](https://user-images.githubusercontent.com/92710332/208011567-af694ec1-a45d-40cf-8f1f-6664e36969d5.png)
![image](https://user-images.githubusercontent.com/92710332/208011583-5e9f815e-bf29-4161-b1eb-5b17a7a3f4b1.png)

**Comment by 3S-En** [comment]
@TMCFrankLee @Herman1114414

2022/12/26 PM 13:30 會議討論
1. 按照原始設計原理製作發包
2. 請問吸嘴需要更換嗎? 會議最後尚未決定此項目。

**Comment by 3S-En** [comment]
結論：
(1) 按照原始設計原理製作發包
(2) 吸嘴保留原始設計(45天長交期)-先下訂。

**Comment by 3S-En** [comment]
已發包且回廠安裝測試完畢。
