### ISSUE TITLE
AJI 機台停產料件清單

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#12]
@NickLee475 @TMCFrankLee 

目前停產清單
東方馬達替代料，後續需評估機構設計以及電控資料。

[軸控Issue清單.xlsx](https://github.com/NickLee475/3S-FOCI-TMC/files/10215266/Issue.xlsx)

**Comment by TMCFrankLee** [comment]
@3S-En 
1. 除馬達外，其他 IO 模組/元件，是否也有停產情形?
2. 這三顆東方馬達請優先安排單元模組穩定性 overnight 測試

**Comment by 3S-En** [comment]
相關零組件會邊測試邊確認。

由於逆向工程花費時間會較多，且會影響到整體進度時程。

因此目前只有針對已知的問題條列出，後續有遇到會在追加IO模組清單。

東方馬達也已聯繫原廠，後續會持續追蹤。 單元模組穩定性測試也會排定第一優先。

**Comment by TMCFrankLee** [comment]
> 相關零組件會邊測試邊確認。
> 由於逆向工程花費時間會較多，且會影響到整體進度時程。
> 因此目前只有針對已知的問題條列出，後續有遇到會在追加IO模組清單。

如討論，請針對重要的 IO 模組列表確認是否有停產狀況。

**Comment by 3S-En** [comment]
(1) 東方馬達將排列第一優先測試項目，確認其穩定性。
(2) 持續追蹤後續IO測試狀況。

**Comment by 3S-En** [comment]
(1) 東方馬達-LAM2F500MW-1(循環測試3小時無異狀)
(2) 東方馬達-LAM2F500MW-2(循環測試3小時無異狀)

**Comment by 3S-En** [comment]
目前東方馬達循環測試無異狀，後續追蹤 #16 (圖面比對後，機構件需作修改)

**Comment by 3S-En** [comment]
1/3周會決議，此項目進行後續EOL追蹤，並提早繪製圖面及相關工時評估。相關資訊皆在 #16 。

**Comment by TMCFrankLee** [comment]
除馬達外，其他 IO 模組/元件，是否也有停產情形?
