### ISSUE TITLE
BH2 轉接版彎曲

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#17]
@nicklee1943 @TMCFrankLee @Herman1114414 
問題：
1.IKO滑軌到貨，組裝時發現轉接版有些許變形
![image](https://user-images.githubusercontent.com/92710332/210678253-ce8a778f-2bd6-4eda-802a-b3583c976178.png)
![image](https://user-images.githubusercontent.com/92710332/210678271-7a0b214c-0b5b-4de3-bb6c-cf6292c8e824.png)
![image](https://user-images.githubusercontent.com/92710332/210678293-f047936d-7110-471c-9ae2-4bfb679eeb95.png)

目前對策
1. 可裝上，勉強可以使用。

建議後續對應方式
1.發新料件(已修改過設計)，同時會預留限高sensor孔位。

Hint背板需增加兩個孔，Force氣缸固定件重發
![image](https://user-images.githubusercontent.com/92710332/210678350-064eb1ab-3e78-45d1-9dc3-a5f6a751a8c9.png)

**Comment by TMCFrankLee** [comment]
請發新料件，但要注意新料件預計到貨時間，避免精度調校後重新安裝新料件可能造成的精度調校重工發生

**Comment by 3S-En** [comment]
已安裝更換完成。
![image](https://user-images.githubusercontent.com/92710332/218327877-e8302d24-c219-4386-bea6-3a53a359973a.png)
