### ISSUE TITLE
11/14 代理商安裝AJI機台問題

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#2]
@GregAcesolution 
11/14 AJI代理商筑波協助安裝
1. 缺少pump 
   (已從上詮攜帶另一組pump補齊)
2. 機台上電後，裝置管理員驅動程式未安裝
    2.1 USB轉RS232 (下載驅動安裝後正常)
3. 上電測試軟體開啟異常
    3.1原機台上之軟體無法開啟(更換上詮目前廠內可用之軟體)
    3.2更換上詮目前使用之軟體後，AJI全機重設異常
    3.3查看整機後，發現Yaskawa驅動器MDZ 跳出錯誤 F-10
    3.4確認後參數設定異常(此驅動器參數為預設值)
4. 筑波代理商表示全機重設異常則無法繼續進行

Hint: 後續是否能請AJI 原廠協助重設部分，以加速此專案進行。

**Comment by NickLee475** [comment]
1.缺少pump
==> 已排除 (已從上詮攜帶另一組pump補齊)

2. 機台上電後，裝置管理員驅動程式未安裝
    2.1 USB轉RS232
==> 已排除 (下載驅動安裝後正常)

3. 上電測試軟體開啟異常
    3.1原機台上之軟體無法開啟(更換上詮目前廠內可用之軟體)
    3.2更換上詮目前使用之軟體後，AJI全機重設異常
    3.3查看整機後，發現Yaskawa驅動器MDZ 跳出錯誤 F-10
    3.4確認後參數設定異常(此驅動器參數為預設值)
==> Follow up : https://github.com/NickLee475/3S-FOCI-TMC/issues/8

4. 筑波代理商表示全機重設異常則無法繼續進行
==> Follow up : https://github.com/NickLee475/3S-FOCI-TMC/issues/8
