### ISSUE TITLE
11/15 AJI驅動器參數比對分析

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#3]
@GregAcesolution @NickLee475 
11/15 上詮AJI機台備份參數(Yaskawa參數備份)
1. 進行AJI機台參數比對(針對Yaskawa部分)
2. 總共七顆驅動器，僅兩顆參數一模一樣，其餘參數皆不盡相同

Hint：最主要不相同部分為驅動器方向不同。請問原先此機台是否有左右機問題? 或是有當初的設備的spec.

![Yaskawa參數](https://user-images.githubusercontent.com/92710332/202632388-b07a08ec-c1ad-4bea-9659-758cbe943eeb.JPG)

**Comment by NickLee475** [comment]
Follow up : https://github.com/NickLee475/3S-FOCI-TMC/issues/8
