### ISSUE TITLE
11/17 筑波代理商到廠安裝設定

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#4]
@GregAcesolution 
1. 筑波代理商上午到場協助安裝設定(Yaskawa驅動器正常)
2. AJI軟體開啟後，全機重設失敗

![AJI機台畫面卡住](https://user-images.githubusercontent.com/92710332/202632799-64d09c48-ddff-4323-a88d-4bcf7eff3cc1.jpg)

**Comment by NickLee475** [comment]
Follow up : https://github.com/NickLee475/3S-FOCI-TMC/issues/8
