### ISSUE TITLE
11/17 Flir相機 IP/Port未設定

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#5]
@GregAcesolution 
11/17 13:00~17:00
1. 由於AJI電腦性能遲緩，因此決議更換電腦。目前更換為研華 I7-3770 win7-64bit
2. 同時還原為廣化影像軟體開發系統，進行Flir相機連線
3. 連線過程發現Flir相機均未設定IP
4. 同時調光器的Comport是否正確設定?

Hint：是否此IP未設定正確因此導致全機無法重設?在麻煩AJI代理商協助處理。

**Comment by NickLee475** [comment]
1. 由於AJI電腦性能遲緩，因此決議更換電腦。目前更換為研華 I7-3770 win7-64bit
==> @3S-En 已準備提供報價規格

2. 同時還原為廣化影像軟體開發系統，進行Flir相機連線
3. 連線過程發現Flir相機均未設定IP
4. 同時調光器的Comport是否正確設定?
==> Follow up : https://github.com/NickLee475/3S-FOCI-TMC/issues/8
