### ISSUE TITLE
11/24 AJI機台調整相關問題(缺少料件)

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#7]
@GregAcesolution 
1. 缺少CCD3 光源
2. 缺少PCB的吸取治具機構
3. 第一組相機型號與上詮目前運行機台不同。且已停產。

上詮：200萬畫素CMOS, 47 FPS - BFLY-PGE-20E4C/M-CS
  3S ：130萬畫素CCD, 30 FPS - **(停產)** BFLY-PGE-13S2C/M-CS

請問後續該如何處理?是否會有替換料，時程?

**Comment by NickLee475** [comment]
Follow up : https://github.com/NickLee475/3S-FOCI-TMC/issues/8
