### ISSUE TITLE
11/25 全機重設異常需更換料件

### ISSUE THREAD

**Issue by 3S-En** [NickLee475/3S-FOCI-TMC#8]
@NickLee475 @GregAcesolution 

11/25 13:00~20:30
1. 全機重設異常導致取放頭2之模組損毀，需筑波協助更換料件
2. LZ2平台極限Sensor異常(經檢查後發現感測器斷裂導致無訊號)需筑波協助更換
3. 目前撿取tray盤上之對位相機型號與上詮不同，也需筑波協助更換

以上在麻煩筑波壓時間以及更換時程。謝謝

**Comment by GregAcesolution** [comment]
目前剩下的問題，基本上是料的問題才有板法更換，需要Chris那邊跟社長那邊詢問確認

**Comment by TMCFrankLee** [comment]
@ChrisChang888 
請於此處更新下列三項硬體採購/快遞進度

- CCD3 缺少光源模組 : AJI 確認有備品，已安排快遞寄出，預計 12/15 到貨? (Due date : 12/16) 
- CCD1(撿取), CCD4(上看)相機型號與上詮運行機台不同且已停產 : 經確認兩組像機均有現貨，採購中。 (Due date : 12/16)
- BH2 取放臂滑軌毀損 : AJI 已確認廠商有現貨，採購中。(Due date : 12/E)

**Comment by TMCFrankLee** [comment]
經 12/23 跟廣化討論後決議，狀態更新如下
- CCD3 缺少光源模組 : 廣化已收到(Closed)
- CCD1(撿取), CCD4(上看)相機型號與上詮運行機台不同且已停產 : 經確認兩組像機均有現貨，由廣化採購中。 (Due date : 12/E)
- BH2 取放臂滑軌毀損 : 筑波已採購，廠商已從日本寄出，持續追蹤。(Due date : 12/E)

**Comment by 3S-En** [comment]
1/3 狀態更新如下

CCD1(撿取), CCD4(上看)相機型號與上詮運行機台不同且已停產 : 經確認兩組像機均有現貨，由廣化採購中。

- 採購回復1/10到貨。

BH2 取放臂滑軌毀損 : 筑波已採購，廠商已從日本寄出，持續追蹤。(Due date : 12/E)

- 1/3 17:10到貨! 安排1/4組裝復原。

**Comment by 3S-En** [comment]
1/13 狀態更新如下

CCD1(撿取), CCD4(上看)相機型號與上詮運行機台不同且已停產 : 經確認兩組像機均有現貨，由廣化採購中。

採購回復1/10到貨。1/10下午到貨，1/11已安裝完畢。
